tosca_definitions_version: tosca_2_0

profile: community.tosca.technology.k8s:0.1

description: >-
  TOSCA Kubernetes Profile

imports:
  - meta.yaml
  - core.yaml
  - apps.yaml
  - storage.yaml
  - networking.yaml
  - rbac.yaml

