tosca_definitions_version: tosca_2_0

profile: io.kubernetes:1.35

description: >-
  TOSCA Kubernetes Profile

imports:
  - meta.yaml
  - core.yaml
  - apps.yaml
  - storage.yaml
  - networking.yaml
  - rbac.yaml

